spring:
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedHeaders: "*"
#            allowedMethods: "*"
  security:
    filter:
      order: 10
  jackson:
    serialization:
      indent-output: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ron1104
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password: password
    max-active: 1
    initialSize: 1
    tomcat:
      initial-size: 1
      testOnBorrow: true
      validationQuery: SELECT 1
    maxIdle: 1
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      connectionTimeout: 120000
      idleTimeout: 300000
      leakDetectionThreshold: 300000
    #driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      naming:
        naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    #path: /swagger-ui/index.html
    operationSorter: method
  api-docs:
    path: /api-docs
application:
  security:
    jwt:
      secret-key: q+QgId0EKAQ53YG3dNelFqlqTteekylCqjRDj3tb71E=
      expiration: 10800000 #expires in 3 hours (1000 * 180 * 60) / 1 day is 86400000
      refresh-token:
        expiration: 32400000 #expires in 9 hours
booking:
  allowable:
    number-of-weeks: 2
    number-of-months: 2
    event-days: SUNDAY,SATURDAY,FRIDAY,TUESDAY,THURSDAY
    filter-flag:
      enabled: true #allow if true
server:
  port: 8080