openapi: 3.0.1
info:
  title: Booking Manager API
  description: Booking Data Rest for Room Reservation
  termsOfService: Terms of Services...
  contact:
    name: JFCM Mandaluyong
    url: http://jfcm-manda/dummy/url
    email: ron.cando04@gmail.com
  license:
    name: Booking Manager API 1.0.0
    url: http://jfcm-manda/dummy/url
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: LOCAL ENV
paths:
  /booking-api/v1/records/update-user/{id}:
    put:
      tags:
        - users-resources
      operationId: updateUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersEntity'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/update-simbahay/{id}:
    put:
      tags:
        - simbahay-resources
      operationId: updateSimbahayById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimbahayGroupsEntity'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/update-cluster-group/{id}:
    put:
      tags:
        - clusters-resources
      operationId: updateUserById_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClusterGroupsEntity'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/auth/update-password/{id}:
    put:
      tags:
        - user-authentication-resources
      operationId: updatePassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/reservations/add-reservation:
    post:
      tags:
        - reservation-resources
      operationId: addReservation
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/add-user:
    post:
      tags:
        - users-resources
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/add-simbahay:
    post:
      tags:
        - simbahay-resources
      operationId: addSimbahayGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimbahayGroupsEntity'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/add-cluster:
    post:
      tags:
        - clusters-resources
      operationId: addClusterGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClusterGroupsEntity'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/auth/signup:
    post:
      tags:
        - user-authentication-resources
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/auth/signin:
    post:
      tags:
        - user-authentication-resources
      operationId: signin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/users:
    get:
      tags:
        - users-resources
      operationId: getAllUsers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/user/{id}:
    get:
      tags:
        - users-resources
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/simbahay:
    get:
      tags:
        - simbahay-resources
      operationId: getAllSimbahays
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/simbahay/{id}:
    get:
      tags:
        - simbahay-resources
      operationId: getSimbahayById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/cluster/{id}:
    get:
      tags:
        - clusters-resources
      operationId: getClusterById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/all-cluster-groups:
    get:
      tags:
        - clusters-resources
      operationId: getAllClusterGroups
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/delete-user/{id}:
    delete:
      tags:
        - users-resources
      operationId: deleteMember
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
  /booking-api/v1/records/delete-simbahay/{id}:
    delete:
      tags:
        - simbahay-resources
      operationId: deleteSimbahay
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /booking-api/v1/records/delete-cluster-group/{id}:
    delete:
      tags:
        - clusters-resources
      operationId: deleteClusterGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    GrantedAuthority:
      type: object
      properties:
        authority:
          type: string
    UsersEntity:
      required:
        - address
        - birthday
        - cluster
        - clusterCode
        - contactNumber
        - emailAdd
        - firstName
        - lastName
        - password
        - role
        - simbahayCode
        - simbahayName
        - status
        - userName
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        emailAdd:
          type: string
        contactNumber:
          type: string
        address:
          type: string
        birthday:
          type: string
        role:
          type: string
          enum:
            - USER
            - OFFICE_ADMIN
            - SOW_ADMIN
            - PASTOR
            - ELDER
            - AE
            - MINISTRY_HEAD
            - SIMBAHAY_LEADER
        status:
          type: string
        cluster:
          type: string
        clusterCode:
          type: string
        simbahayName:
          type: string
        simbahayCode:
          type: string
        userName:
          type: string
        password:
          type: string
        enabled:
          type: boolean
        authorities:
          type: array
          items:
            $ref: '#/components/schemas/GrantedAuthority'
        username:
          type: string
        accountNonExpired:
          type: boolean
        accountNonLocked:
          type: boolean
        credentialsNonExpired:
          type: boolean
    JwtAuthenticationResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        token:
          type: string
        data:
          type: object
        status:
          type: integer
          format: int32
        responsecode:
          type: string
        message:
          type: string
    SimbahayGroupsEntity:
      type: object
      properties:
        id:
          type: string
        simbahayName:
          type: string
        simbahaySchedule:
          type: string
        cluster:
          type: string
        clusterCode:
          type: string
        simbahayLeader1:
          type: string
        simbahayLeader2:
          type: string
        totalMembers:
          type: integer
          format: int32
        location:
          type: string
        status:
          type: string
    ClusterGroupsEntity:
      type: object
      properties:
        clusterCode:
          type: string
        clusterName:
          type: string
        clusterLeader1:
          type: string
        clusterLeader2:
          type: string
        totalSimbahay:
          type: integer
          format: int32
    SigninRequest:
      type: object
      properties:
        userName:
          type: string
        password:
          type: string